#name: tnpis
#description: "A new Flutter project."
#
#publish_to: 'none'
#version: 1.0.0+1
#
#environment:
#  sdk: '>=3.4.3 <4.0.0'
#
#
#dependencies:
#  flutter:
#    sdk: flutter
#  flutter_launcher_icons: "^0.13.1"
#
#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/icon.png"
#
#
#
#  cupertino_icons: ^1.0.6
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#
#  flutter_lints: ^3.0.0
#
#
#flutter:
#
#
#  uses-material-design: true
#
#
flutter:
  assets:
    - assets/images/
  uses-material-design: true
name: tnpis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  cupertino_icons: ^1.0.6
  local_captcha: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

#flutter:

#  assets:
#    - assets/images/emblem-light.jpg
#    - assets/images/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
